name: echo test
on:  push
   
jobs:
  echo-test-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch test.env.json
          echo { >> test.env.json
          echo '"username": "lin",' >> test.env.json
          echo '"password": "pass"' >> test.env.json
          echo } >> test.env.json
          #echo hello >> test.env.json
          cat test.env.json

