on:
  push:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{${GITHUB_REF#refs/heads/} == 'test'}}
      - run: echo "${GITHUB_REF_CONTEXT#refs/heads/}"
    env:
      GITHUB_REF_CONTEXT: ${{ github.ref }}
